### PR TITLE
remove go.mod go.sum

### PR DESCRIPTION
**Pull request by ghost**
looking at btcsuite/btcutil it does not have a go.mod - it seems I accidentally added one to ltcsuite/ltcutil in a recent PR.  This causes a recursive dependency between ltcd and ltcutil - each referencing ever older versions of each other.  To break this we remove go.mod matching btcsuite.

### CODE REVIEW

**Comment by chappjc** [comment]
The go mod files were not added accidentally. `github.com/ltcsuite/ltcutils` needs to be a go module as ltcd `require`s it in it's go.mod.  Removing these files from ltcutils does not solve anything.  A proper solution might be one of :
1. Create modules in the ltcd repository for: `chaincfg`, `wire`, `btcec`, and `txscript`. OR
2. Move ltcutil into the ltcd repository.

The actual problem I see is that txscript (github.com/ltcsuite/ltcd/txscript) imports ltcutil, which imports txscript.  The module definitions aren't central to this problem.

**Comment by ghost** [comment]
@chappjc btcutil and ltcutil do not have go.mod.  it was there in ltcutil for only 1 day when my PR #2 accidentally introduced it and broke the build.  

If btcutil were to introduce a go.mod we'd follow suite here in ltcutil.

**Comment by chappjc** [comment]
I see. Thanks for the explanation.  Hopefully the circular txscript<-->ltcutil dependency issue is resolved upstream so that the daemon can make use of updated versions of the util package.

**Comment by chappjc** [comment]
Actually on closer inspection the package dependency isn't circular as I initially thought.  I do appreciate that it's annoying that both modules require each other since that makes updating a bit annoying and it is odd to end up with a ltcutil line in ltcutil's own go.sum, but afaict everything builds without error as long as *the packages in the modules* aren't depending on each other (at least when I tried it in btcutil).

The only reason I'm commenting on the issue is that in using ltcutil (or btcutil) it would be preferable for them to be modules with their dependencies locked down.  Perhaps I should raise an issue with btcsuite?  Thanks again for the response.

**Pull request merged**
